#!/home/maui/repos/UAV-gstreamer-jetson/venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import asyncio
from examples.run_server import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(asyncio.run(main()))


# import asyncio
# from examples.run_server import main
# if __name__ == '__main__':
#     print(__doc__)
#     asyncio.run(main())