
camera_names = ['0', '1', '2', '3']    # ['front', 'down', 'gimbal']
camera_ip_ports = [5000, 5001, 5002, 5003]      # [5000, 5001, 5010]
camera_udp_decoder = 'h264'
# camera_udp_decoder = 'h265'
camera_component = 11

gimbal_component = 12

[mavlink]
source_system = 111
target_system = 222
#connection = "udpin:192.168.1.175:14445"     # this is the wlan IP of this pc
#connection = "/dev/ttyUSB0"  # holybro telemetry radio

# connection = "udpin:192.168.1.79:14445"
# connection = "/dev/ttyACM0" "/dev/ttyUSB1"
# connection, con2 = "/dev/ttyUSB0", "/dev/ttyUSB1"
# connection = "udpout:192.168.122.84:14445"
connection = "udpin:10.42.0.1:14445"

