cam_name = 'cam_3'

[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer_video_src]
loglevel = 'DEBUG'   # todo add loglevel to all pipelines and to gst_utils
width = '*rpi_raw_width*'
height = '*rpi_raw_height*'
fps = '*rpi_raw_fps*'

pipeline = [
    'nvarguscamerasrc sensor_id=1 ! video/x-raw(memory:NVMM), width={width}, height={height}, format=NV12, framerate={fps}/1',
    'tee name=t',
    't. ! queue',
    'nvvidconv',  # needs this to isolate the camera from the interpipesink otherwise segfault errors etc
    'interpipesink name={cam_name} '
]


# streaming pipelines

[gstreamer_udpsink]
host = '*camera_UDP_IP*'     # overwrite with server_config.toml
port = '*cam_3_UDP_port*'    # overwrite with server_config.toml
bitrate = 2000000

width = '*rpi_stream_width*'
height = '*rpi_stream_height*'
fps = '*rpi_stream_fps*'

pipeline = [
    'interpipesrc listen-to={cam_name} is-live=true format=time',
    'queue',
    'nvvidconv',
    #'videorate',  # Add videorate to change the frame rate
    'video/x-raw,width={width},height={height},framerate={fps}/1',  # Set the new frame rate
    'nvvidconv',
    'nvv4l2h264enc bitrate={bitrate}',
    'rtph264pay config-interval=1 ! udpsink host={host} port={port}  sync=false',
]

[gstreamer_jpg_filesink]
quality = 95
filenames = '%05d.jpg'
index = 0

pipeline = [
    'interpipesrc listen-to={cam_name} is-live=false allow-renegotiation=true format=time',
    'queue',
    'videorate drop-only=true skip-to-first=true ! video/x-raw(memory:NVMM), framerate=30/10',
    'nvvidconv ! video/x-raw(memory:NVMM), format=I420',
    'nvjpegenc quality={quality} idct-method=1',
    'multifilesink location={save_path}/{cam_name}/{filenames} index={index} max-files=5400',
]
